---
subscriptions:
  konflux:
    enabled: false
    description: Community Konflux Operator
    apiResource: konfluxes.konflux.konflux-ci.dev
    namespace: konflux-operator
    name: konflux-operator
    channel: stable-v0.2
    source: community-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces: []
  openshiftCertManager:
    enabled: false
    description: Red Hat Cert-Manager Operator
    apiResource: certificates.cert-manager.io
    namespace: cert-manager-operator
    name: openshift-cert-manager-operator
    channel: stable-v1
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces: []
  openshiftKeycloak:
    enabled: false
    description: Red Hat Keycloak Operator
    apiResource: keycloaks.k8s.keycloak.org
    namespace: rhbk-operator
    name: rhbk-operator
    channel: stable-v26.4
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces: []
  openshiftPipelines:
    enabled: false
    description: OpenShift Pipelines Operator
    apiResource: tektonconfigs.operator.tekton.dev
    namespace: openshift-operators
    name: openshift-pipelines-operator-rh
    channel: pipelines-1.20
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  openshiftTrustedArtifactSigner:
    enabled: false
    description: Red Hat Trusted Artifact Signer Operator
    apiResource: securesigns.rhtas.redhat.com
    namespace: openshift-operators
    name: rhtas-operator
    channel: stable-v1.4
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  trustedProfileAnalyzer:
    enabled: false
    description: Red Hat Trusted Profile Analyzer
    apiResource: trustedprofileanalyzers.rhtpa.io
    namespace: tsf-tpa
    name: rhtpa-operator
    channel: stable-v1.1
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces:
        - tsf-tpa
